version: '2.2'
services:
  appointment:
    build:
      context: ./
      dockerfile: Dockerfile
    image: springboot-app-dockercompose
    ports:
      - 8080
    networks:
      - network1
    scale: 1

networks:
  network1: